
class Protocol:
    """ Pseudo Enumeration for the communication protocol
    """
    # GENERAL
    ECHO = 0
    RESTART = 1
    # GET
    GETDIR = 10
    GETSTATUS = 11
    GETDBSTATUS = 12
    GETFILEHASH = 13
    GETDIRHASH = 14
    # INPUTDB
    MAKEPATHRELATIVE = 20
    MAKEHDF5TXT = 22
    ADDHDF5 = 23
    GETFILECONTENT = 24
    WRITEFILECONTENT = 25
    ADDCAFFEVERSION = 26
    GETHASH = 27
    # HARDWARE
    GETHARDWARE = 30
    SCANHARDWARE = 31
    SETHARDWARE = 32
    GETPLATFORM = 33
    # SESSION
    SESSION = 40
    CREATESESSION = 41
    CONNECTTOSESSION = 42
    GETSESSIONS = 43
    DELETESESSION = 44
    CLONESESSION = 45
    DISCONNECTSESSION = 46
    # CAFFE-VERSIONS
    GETCAFFEVERSIONS = 50
    ADDCAFFEVERSIONS = 51
    SETCURRENTCAFFEVERSION = 52
    REMOVECAFFEVERSION = 53  
    GETDEFAULTCAFFEVERSION = 54
    GETCAFFERESTART = 55


class SessionProtocol:
    """ Pseudo Enumeration for the communication protocol for subkeys in remote sessions
    """

    GETITERATION = 0
    GETMAXITERATION = 1
    GETSNAPSHOTS = 2
    GETSTATE = 3
    SETMAXITERATION = 4
    GETPRETRAINED = 5

    SAVE = 10
    CHECKFILES = 11
    CHECKTRAINING = 12

    GETSTATEDICT = 20
    SETSTATEDICT = 21

    PRINTLOG = 30
    UPDATEPARSER = 31
    UPDATESTATE = 32
    UPDATEKEYS = 33
    ADDSNAPSHOT = 34
    PARSEHANDLE = 35
    FETCHPARSERDATA = 36

    START = 40
    PAUSE = 41
    PROCEED = 42
    TAKESNAPSHOT = 43

    LOADINTERNALNET = 50
    LOADDEPLOYEDNET = 51
    LOADNETPARAMETER = 52
    LOADCAFFEMODEL = 53

    RESET = 98
    DELETE = 99
